// Host test for the BLE wire codec (no Pico SDK, no hardware). Parses inputs
// generated by cbor2 and writes CBOR outputs that the Python cross-check feeds
// through savia_py's OWN codec -- proving TerraLink-compatible output.
// See test/crosscheck_ble_codec.py.
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "savia/ble_codec.h"
#include "savia/types.h"

static size_t read_file(const char *path, uint8_t *buf, size_t cap) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return 0; }
    size_t n = fread(buf, 1, cap, f);
    fclose(f);
    return n;
}
static void write_file(const char *path, const uint8_t *buf, size_t n) {
    FILE *f = fopen(path, "wb");
    if (!f) { perror(path); return; }
    fwrite(buf, 1, n, f);
    fclose(f);
}
static void emit_frame(const uint8_t *frame, size_t len, void *ctx) {
    FILE *f = (FILE *) ctx;
    uint8_t hdr[2] = { (uint8_t)(len >> 8), (uint8_t)(len & 0xff) };
    fwrite(hdr, 1, 2, f);
    fwrite(frame, 1, len, f);
}

int main(void) {
    uint8_t in[256];
    size_t n;

    // --- parse data_request (from cbor2) ---
    n = read_file("/tmp/savia_req.cbor", in, sizeof(in));
    assert(n > 0);
    ble_data_request_t dr;
    assert(ble_parse_data_request(in, n, &dr));
    assert(dr.version == 1 && strcmp(dr.op, "get") == 0 && strcmp(dr.kind, "raw") == 0);
    assert(dr.has_from && dr.from_ms == 1000 && dr.has_to && dr.to_ms == 2000 &&
           dr.has_limit && dr.limit == 50);
    printf("test_ble_codec: data_request parse OK\n");

    // indefinite-length map (kotlinx-cbor style): {v:1, op:"get", kind:"raw"}
    static const uint8_t indef[] = {
        0xBF, 0x61, 'v', 0x01, 0x62, 'o', 'p', 0x63, 'g', 'e', 't',
        0x64, 'k', 'i', 'n', 'd', 0x63, 'r', 'a', 'w', 0xFF };
    ble_data_request_t dr2;
    assert(ble_parse_data_request(indef, sizeof(indef), &dr2));
    assert(dr2.version == 1 && strcmp(dr2.op, "get") == 0 && strcmp(dr2.kind, "raw") == 0);
    printf("test_ble_codec: indefinite-length data_request parse OK\n");

    // Real TerraLink bytes captured over BLE: {v:1, op:"count", kind:"raw",
    // from:null, to:null} -- indefinite map + CBOR nulls.
    static const uint8_t tl_count[] = {
        0xbf, 0x61,0x76,0x01, 0x62,0x6f,0x70, 0x65,0x63,0x6f,0x75,0x6e,0x74,
        0x64,0x6b,0x69,0x6e,0x64, 0x63,0x72,0x61,0x77,
        0x64,0x66,0x72,0x6f,0x6d, 0xf6, 0x62,0x74,0x6f, 0xf6, 0xff };
    ble_data_request_t dr3;
    assert(ble_parse_data_request(tl_count, sizeof(tl_count), &dr3));
    assert(dr3.version == 1 && strcmp(dr3.op, "count") == 0 && strcmp(dr3.kind, "raw") == 0);
    assert(!dr3.has_from && !dr3.has_to);
    printf("test_ble_codec: TerraLink count request (null from/to) parse OK\n");

    // --- parse time_sync ---
    n = read_file("/tmp/savia_timesync.cbor", in, sizeof(in));
    assert(n > 0);
    uint64_t ms = 0;
    assert(ble_parse_time_sync(in, n, &ms));
    assert(ms == 1700000000000ULL);
    printf("test_ble_codec: time_sync parse OK (ms=%llu)\n", (unsigned long long) ms);

    // --- parse weather ---
    n = read_file("/tmp/savia_weather.cbor", in, sizeof(in));
    assert(n > 0);
    assert(ble_parse_weather(in, n));
    printf("test_ble_codec: weather parse OK\n");

    // --- parse config patch (from cbor2) ---
    n = read_file("/tmp/savia_config_patch.cbor", in, sizeof(in));
    assert(n > 0);
    ble_config_patch_t cp;
    assert(ble_parse_config_patch(in, n, &cp));
    assert(cp.has_name && strcmp(cp.name, "Huerta-1") == 0);
    assert(cp.version == 1 && strcmp(cp.op, "set") == 0 && cp.has_sleep_s && cp.sleep_s == 300);
    assert(cp.has_deep_sleep && cp.deep_sleep == true);
    assert(cp.has_capture_s && cp.capture_s == 120 && cp.has_daily_hour && cp.daily_hour == 6);
    assert(cp.has_mock && cp.mock == true && cp.has_log_level && cp.log_level == 0);
    printf("test_ble_codec: config patch parse OK\n");

    // indefinite-length config patch (kotlinx-cbor): {v:1, op:"set", sleep_s:300, deep_sleep:true}
    static const uint8_t cp_indef[] = {
        0xBF, 0x61, 'v', 0x01, 0x62, 'o', 'p', 0x63, 's', 'e', 't',
        0x67, 's', 'l', 'e', 'e', 'p', '_', 's', 0x19, 0x01, 0x2C,
        0x6A, 'd', 'e', 'e', 'p', '_', 's', 'l', 'e', 'e', 'p', 0xF5, 0xFF };
    ble_config_patch_t cp2;
    assert(ble_parse_config_patch(cp_indef, sizeof(cp_indef), &cp2));
    assert(cp2.version == 1 && strcmp(cp2.op, "set") == 0 && cp2.has_sleep_s && cp2.sleep_s == 300);
    assert(cp2.has_deep_sleep && cp2.deep_sleep == true);
    printf("test_ble_codec: indefinite-length config patch parse OK\n");

    uint8_t buf[512];
    size_t l;

    // --- parse ingest (timestamped upsert points from cbor2) ---
    n = read_file("/tmp/savia_ingest.cbor", in, sizeof(in));
    assert(n > 0);
    savia_reading_t ing[8];
    bool iok;
    size_t ni = ble_parse_ingest(in, n, ing, 8, &iok);
    assert(iok && ni == 3);
    assert(ing[0].kind == READING_AIR_TEMPERATURE && ing[0].ts_ms == 1781996400000ULL);
    assert(ing[0].depth_cm == 0 && ing[0].port == 1);                  // air defaults
    assert(ing[2].kind == READING_SOIL_MOISTURE && ing[2].depth_cm == 30);
    l = ble_serialize_readings(ing, ni, buf, sizeof(buf));             // echo for Python check
    assert(l > 0);
    write_file("/tmp/savia_ingest_parsed.cbor", buf, l);
    l = ble_serialize_ingest_ok(3, 1, buf, sizeof(buf));              // 3 created, 1 updated
    assert(l > 0);
    write_file("/tmp/savia_ingest_ok.cbor", buf, l);
    printf("test_ble_codec: ingest parse OK (%zu points)\n", ni);

    // --- readings + chunking ---
    savia_reading_t rows[2] = {
        { .ts_ms = 1700000000000ULL, .port = 1, .depth_cm = 10,
          .kind = READING_SOIL_MOISTURE, .value = 0.75f },
        { .ts_ms = 1700000000000ULL, .port = 1, .depth_cm = 30,
          .kind = READING_SOIL_MOISTURE, .value = 0.77f },
    };
    l = ble_serialize_readings(rows, 2, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_readings.cbor", buf, l);
    FILE *ff = fopen("/tmp/savia_frames.bin", "wb");
    assert(ff);
    ble_chunk_encode(buf, l, 8, emit_frame, ff);
    fclose(ff);

    // --- aggregations ---
    uint64_t hour0 = 1700000000000ULL - (1700000000000ULL % 3600000ULL);
    savia_aggregate_t aggs[1] = {{ .hour_ms = hour0, .port = 1,
        .kind = READING_SOIL_MOISTURE, .depth_cm = 10,
        .count = 3, .mean = 0.6f, .min = 0.5f, .max = 0.7f }};
    l = ble_serialize_aggregations(aggs, 1, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_aggs.cbor", buf, l);

    // --- predictions (one full, one with null port/confidence) ---
    savia_prediction_t preds[2];
    memset(preds, 0, sizeof(preds));
    preds[0].ts_ms = 1700000000000ULL;
    strcpy(preds[0].model, "lstm-hs30");
    strcpy(preds[0].kind, "hs30_forecast");
    preds[0].has_port = true; preds[0].port = 1;
    preds[0].value = 0.66f;
    preds[0].has_confidence = true; preds[0].confidence = 0.9f;
    preds[1].ts_ms = 1700003600000ULL;
    strcpy(preds[1].model, "lstm-hs30");
    strcpy(preds[1].kind, "hs30_forecast");
    preds[1].has_port = false;
    preds[1].value = 0.64f;
    preds[1].has_confidence = false;
    l = ble_serialize_predictions(preds, 2, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_preds.cbor", buf, l);

    // --- status + count ---
    l = ble_serialize_status(12345, 1700000000000ULL, 0, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_status.cbor", buf, l);
    l = ble_serialize_count(42, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_count.cbor", buf, l);

    // --- config snapshot (device card + sleep + sensors + gpio map) + ack ---
    station_config_t cfg;
    config_load_defaults(&cfg);
    savia_device_id_t dev = { .model = "Raspberry Pi Pico WH", .mcu = "RP2040",
                              .fw = "0.1.0-c" };
    l = ble_serialize_config(&dev, &cfg, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_config.cbor", buf, l);
    l = ble_serialize_config_ack(true, 300, true, NULL, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_config_ack.cbor", buf, l);

    // --- logs (array of text lines, served chunked via kind="logs") ---
    const char *loglines[3] = { "boot ok", "BLE: central connected",
                                "sched: daily cycle (hour=20)" };
    l = ble_serialize_logs(loglines, 3, buf, sizeof(buf));
    assert(l > 0);
    write_file("/tmp/savia_logs.cbor", buf, l);

    printf("test_ble_codec: serialized readings/aggs/preds/status/count/config\n");
    printf("test_ble_codec: OK\n");
    return 0;
}
