#!/usr/bin/env sh
# Embed the int8 LSTM as a C array for the on-device (RP2350) build.
#
# The TFLite Micro path in src/system/inference.c needs the model compiled into
# the firmware (no filesystem on the Pico). This turns the .tflite into a header
# with `g_lstm_hs30_model[]` + its length. Run once whenever the model changes.
#
# Usage:  sh tools/embed_model.sh [path/to/lstm_hs30_int8.tflite]
set -e
cd "$(dirname "$0")/.."

SRC="${1:-../../docs/sensor_documentation/model/modelo_lstm/lstm_hs30_int8.tflite}"
OUT="include/savia/lstm_hs30_int8_model.h"

if [ ! -f "$SRC" ]; then
  echo "error: model not found: $SRC" >&2
  exit 1
fi

{
  echo "// Auto-generated by tools/embed_model.sh -- do not edit."
  echo "// int8 LSTM HS30 model for on-device (RP2350) TFLite Micro inference."
  echo "#ifndef SAVIA_LSTM_HS30_INT8_MODEL_H"
  echo "#define SAVIA_LSTM_HS30_INT8_MODEL_H"
  echo "#include <stdint.h>"
  # 16-byte alignment: TFLM requires the model buffer aligned. The GCC attribute
  # works in both C and C++ (arm-none-eabi-gcc) with no extra header.
  echo "__attribute__((aligned(16))) const unsigned char g_lstm_hs30_model[] = {"
  od -An -v -tx1 "$SRC" | sed 's/[0-9a-f]\{2\}/0x&,/g'
  echo "};"
  echo "const unsigned int g_lstm_hs30_model_len = sizeof(g_lstm_hs30_model);"
  echo "#endif // SAVIA_LSTM_HS30_INT8_MODEL_H"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$SRC") bytes of model)"
